name: HelloWorldService
on:
  - push:
      branches:
        - master

  - pull_request:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4
    - uses: olafurpg/setup-scala@v11
      with:
        java-version: adopt@1.11
    - name: Run Tests
      reun: sbt test



