name: HelloWorldService
on:
  push:
    branches: [main]

  pull_request:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11
      - name: Run Tests
        working-directory: ./ecr
        run: ./ecr sbt test



